name: Compare Configuration

on:
  push:
    branches: [ main ]

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Produce some output
      - name: Read Submitted Config
        id: submitted
        run: |
          more submitted-config.txt >> $GITHUB_OUTPUT

      # Step 2: Compare network configuration
      - name: Compare with base config
        if: ${{ steps.submitted.outputs.result == 'hello' }}
        run: echo "The string matches 'hello'!"
